org: glasswall
service: jpi

provider:
  name: aws
  runtime: python3.7
  stage: ${env:STAGE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "*"
  cronInterval: ${env:PAGERDUTY_CRON_INTERVAL}
  logEntriesPollingInterval: ${env:LOG_ENTRIES_POLL_INTERVAL}
  environment:
    INCIDENTS_TABLE: ${self:custom.incidentsTableName}
    LOG_ENTRIES_TABLE: ${self:custom.logEntriesTableName}
    CONFIG_TABLE: ${self:custom.configTableName}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  cron:
    handler: jpi/pd_cron.handler
    events:
      - schedule: 'rate(${self:provider.cronInterval})'
  log_entries_polling:
    handler: jpi/polling.handler
    events:
      - schedule: 'rate(${self:provider.logEntriesPollingInterval})'

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-wsgi
  - serverless-dynamodb-local

custom:
  incidentsTableName: 'incidents-${self:provider.stage}'
  logEntriesTableName: 'log-entries-${self:provider.stage}'
  configTableName: 'config-${self:provider.stage}'
  wsgi:
    app: jpi/app.app
    packRequirements: false
    pythonBin: python3
  pythonRequirements:
    dockerizePip: true
  dynamodb:
    start:
      port: 8002
      inMemory: true
      migrate: true
    stages:
      - dev
      - test
  dotenv:
    basePath: ./

package:
  exclude:
    - env/**

resources:
  Resources:
    IncidentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.incidentsTableName}
        AttributeDefinitions:
          - AttributeName: incidentId
            AttributeType: S
        KeySchema:
          - AttributeName: incidentId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    LogEntriesTableName:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.logEntriesTableName}
        AttributeDefinitions:
          - AttributeName: logEntryId
            AttributeType: S
        KeySchema:
          - AttributeName: logEntryId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ConfigTableName:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.configTableName}
        AttributeDefinitions:
          - AttributeName: parameterName
            AttributeType: S
        KeySchema:
          - AttributeName: parameterName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
